package com.mygdx.game.model.network.massage.serverResponse;

public enum ServerResponseType {
    DENY,
    LOGIN_CONFIRM,
    LOGIN_DENY,

    SECURITY_QUESTION_SET,
    SIGN_IN_CONFIRM,
    SIGN_IN_DENY,

    FRIEND_REQUEST,
    INVITE_TO_PLAY,

    PLAY_CARD_RESPONSE,
    CHANGE_SCREEN,
    GAME_TURN_DECIDE, END_ROUND, END_GAME, START_GAME,
    CHAT, GET_PUBLIC_GAMES, GET_ALL_USERS,
    RE_DRAW,
    RETURN_TO_GAME, JOIN_AS_SPECTATOR, CONNECTION_LOST, RANDOM_GAMES_LIST, GOTO_TOURNAMENT_NEXT_ROUND, START_GAME_ERROR, JOIN_TOURNAMENT_ERROR;
}
