package com.mygdx.game.model.network.massage.serverResponse;

public enum ServerResponseType {
    SESSION_TIME_OUT,
    CONFIRM,
    DENY,
    LOGIN_CONFIRM,
    LOGIN_DENY,

    SECURITY_QUESTION_SET,
    SIGN_IN_CONFIRM,
    SIGN_IN_DENY,

    FRIEND_REQUEST,
    GET_FRIENDS,

    INVITE_TO_PLAY,
    INVITE_TO_PLAY_RESPONSE,

    PLAY_CARD_RESPONSE,
    CHANGE_SCREEN,
    GAME_TURN_DECIDE, END_ROUND, END_GAME, START_GAME, PLAY_CARD_PERMISSION, CHAT, GET_PUBLIC_GAMES, GET_ALL_USERS,
    RE_DRAW,
    RETURN_TO_GAME, JOIN_AS_SPECTATOR;
}
