package com.mygdx.game.model.network.massage.clientRequest;

public enum ClientRequestType {
    SIGN_IN,
    ABORT_SIGN_IN,
    SET_SECURITY_QUESTION,

    LOGIN,

    FRIEND_REQUEST,
    GET_FRIEND_REQUESTS,
    GET_FRIENDS,

    START_GAME,
    INVITE_ANSWER,
    CHANGE_MENU,
    PLAY_CARD_REQUEST,
    TURN_DECIDE,
    CARD_SELECT_ANSWER,
    SPECTATOR_CHAT, GET_PUBLIC_GAMES, JOIN_AS_SPECTATOR, GET_ALL_USERS,
    RE_DRAW,
    PASS_ROUND, CHAT

}
